= Allerhand Ménongen

(Luxemburger Wort 29/9/1948)

== Zur Lösung der Wohnungsfrage

Zur Hebung der Wohnungsnot besonders
in den Städten und Industriezentren werden 
immer wieder, und mit Recht, Staat
und Gemeinden als Helfer in der Not angerufen. 
An diese ergeht die Bitte, „billige
Wohnungen" zum Verkaufe oder zur Vermietung 
zu errichten sowie jene Personen,
die selbst ein Eigenheim bauen möchten,
durch Bewilligung von Bau pro mien zu
unterstützen.

Die Verwirklichung dieser Vorschläge
bedeutet keine allzu willkommene Lösung
für die künftigen Bewohner der Neubauten,
Als Eigentümer müssen sie einen Kostenpreis 
zahlen, der annähernd vier mal höher
ist wie vor dem letzten Weltkrieg; als Mieter 
sehen sie ihren bisherigen Mietpreis
wenigstens verdoppelt, sogar verdreifacht,
denn die Mieten für Neubauten sind gesetzlich 
keiner Einschränkung unterworfen.

Einen Beweis für die Richtigkeit dieser
Behauptungen liefern die im Vorjahre im
Umkreis der Stadt Luxemburg errichteten
Einfamilienhäuser. Die meisten davon begreifen 
fünf Zimmer, werden zu mehr denn
400,000 Fr. verkauft und zu wenigstens
1200 Fr. monatlich vermietet.

Der „Nationalen Gesellschaft für den
Bau billiger Wohnungen" sei wegen dieser
hohen Bau- und Mietpreise keineswegs
ein Vorwurf gemacht, denn Privatleute
hätten ein mit demselben Komfort ausgestattetes 
Wohnhaus nicht billiger bauen
können.

Wer kein Eigenheim besitzt, handelt
demnach in seinem eigenen Interesse, wenn
er möglichst lang in einem vor dem Kriege
erbauten Hause als Mieter bleibt; meist
wrid er nur notgedrungen sich dazu ent-
schließen, als Käufer oder als Mieter in
einen Neubau einzuziehen.

Infolge der hohen Gestehungspreise für
Neubauten sowie der in den letzten Jahren 
bei Versteigerungen erzielten Hauspreise 
zeigen die Mieter besonders in den
letzten Monaten eine beständig steigende
Tendenz.

Sowohl Vermieter als Mieter setzen sich
vielfach hinweg über das Mietgesetz, das
eine Erhöhung von nur fünfzig Prozent der
am ersten Februar 1939 gezahlten Miete
gestattet. Die Eigentümer behaupten, trotz
einer weitem mäßigen Erhöhung des Mietpreises 
stehe dieser noch ziemlich bedeutend 
unter dem, der für Wohnungen in Neubauten 
bezahlt wird. Eine Anzahl Mieter
erkennen die Berechtigung dieser Argumentation 
an, erheben keinen Einspruch
und zahlen. Andere — so unwab, das auch klingen mag — erklären sich un-
aufgefordert zur Zahlung einer höhern
Miete bereit; ein Vorschlag, der von einzelnen 
Eigentümern willig angenommen,
von andern aber mit der Begründung abgelehnt 
wird, man halte sich an die zu
Recht bestehenden Gesetze. '— Wo keine
Einigung zustande kommt, bestehen ge-
spannte Verhältnisse.

So werden denn in nächster Zukunft
immer mehr für Wohnungen gleichen Raumes 
und gleicher Qualität drei höchst
ungleiche Mietpreise zu verzeichnen sein:
der erste, der seit 1939 um fünfzig Prozent
erhöhte, beträgt das anderthalbfache; der
zweite, gesetzwidrige etwas das Doppelte
und der dritte, der in Neubauten,- das
Dreifache der Vorkriegsmiete,

Trotz dieser unangemhmen Begleiter-
scheinungen, müssen Bauen und Baulust
energisch gefördert werden, denn
Gesundheit und Zufriedenheit, die nur in einer
anständigen Wohnung anzutreffen sind,
lassen sich nicht mit Geld abwögen.

Neben dieser radikalen Maßregel wird
eine angemessene Erhöhung der gesetz-
lichen Mieten nicht wenig zur Linderung
der Wohnungsnot beitragen. Das Mietge-
setz hatte da« Gegenteil zur Folge.

Bei der am 31. Dezember verfl. J. stattgefundenen 
Volks- und Wohnungszählung
wurde festgestellt, daß manche Familien,
ohne weitere Einschränkung, zwei oder
drei Zimmer abtreten könnten. Darin
könnten manche der zahlreichen jungen
Paare, die heiraten möchten und vergebens 
eine Wohnung suchen, wenigstens
einige Jahre Unterkunft finden. Die Hausbesitzer 
verhalten sich teilnahmslos, weil
sie der Ansicht sind, bei den hohen Ausgaben 
für Unterhalt und unumgänglich
notwendige Reparaturen, für Steuern, 
Feuerversicherung, Abnutzung usw. fände ihr
Entgegenkommen wenig Anerkennung.
Bei höhern Mietpreisen ständen heute
mehr Wohnungen zur Verfügung und
einem Teil des Wohnungsmangels wäre
abgeholfen.

Der Gesetzgeber wollte den Mietwucher
verhindern; er hat diesen Zweck erreicht;
aber durch die Beibehaltung des gegenwärtigen 
Standes der Mieten leistet er
dem Vermieter und dem Mieter einen
schlechten Dienst.

Er hat, und mit vollem Recht, dazu beigetragen, 
daß das Einkommen der meisten
Bürger seit dem Jahre 1940 um 300 bis
400 Prozent gestiegen ist; dadurch hat er
den Arbeitseifer gehoben, soziale Un-
ruhen verhindert.

So erlaube er denn auch, daß die Bürger, 
die oft durch viele Arbeit und Sorgen
zu Besitztum kamen, einen angemessenen
Ertrag davon erhalten: er erhöhe in
nächster Zeit — die festgesetzten Mietpreise. 
Dann darf er mit Recht und wohl
auch mit Erfolg an das Nationalgefühl der
Hausbesitzer appelieren.

Er möge bedenken, daß ein Ausgleich
der ungleichen Mietsätze sich unwiderstehlich 
anbahnt; im Interesse der Erhaltung
des moralischen Gefühls bei unserer Be-
völkerung soll dies nicht, in Mißachtung
der Gesetze geschehen.

Die Mieter — können und werden dem
Staate — ob seines Vorgehens nicht gram
sein; viele zahlen heute nur etwa den
12. Teil ihres Einkommens als Miete, während 
vor 1940 etwa ein Sechstel als nor-
mal angenommen wurde.

Ruhe und Zufriedenheit können aber nur
dann wieder eintreten, wenn nach einer
möglichst gerechten Regelung der Mietfrage 
Ueberpreise weder gefordert, noch
geboten, noch angenommen werden, wenn
seitens der Behörden mit aller Strenge
gegen jene vorgegangen wird, welche die
Mieter ausbeuten möchten.

In wohl keinem freien Staate Europas
mit Ausnahme von Frankreich, sind die
Mieten niedrgier als bei uns. Aber die dort
seit Jahrzehnten befolgte Wohnungspolitik
hat die Bautätigkeit fast ganz gelähmt
und vielerorts zu solch bedauernswerten
Wohnverhältnissen geführt, daß nur
schwer Remedur zu schaffen ist.
Zur Lösung der Wohnungsfrage laute
also die Parole nicht nur: „Bauen und
nochmals Bauen", sondern; „Bauen und
anständige Mietpreise". P.
